### PR TITLE
Add a config option for manually ecs setting

### PR DESCRIPTION
**Pull request by lightsing**
Add a config option for manually ecs setting.
tested.

### CODE REVIEW

**Comment by m13253** [comment]
Hi,

Thank you for contributing to this project!

But I am sorry that I am not going to merge your contribution, because:

1. Normally you only want to set fake ECS for some domains, not others. You should use some dispatcher frontend (e.g. unbound, dnsmasq, knot-resolver) to write rules for each desired domain.
2. I do not want everyone to set fake ECS unless they really know what they are doing, because it breaks when you take your laptop to cafe.
3. This feature is already implemented in https://github.com/m13253/geodns-injector , and it works both with or without DoH. I do not want to spend double time maintaining the same feature.

I hope you understand my choice. Please give me your opinions and try to convince me if you think I am wrong.—You know, this is an open project and everyone is welcome.

**Comment by lightsing** [comment]
When DoH is running behind a proxy, this feature might be useful if you still wants ecs gets the correct answer. Or we might need to improve the way to get the correct subnet in this case.

**Comment by m13253** [comment]
> When DoH is running behind a proxy, this feature might be useful if you still wants ecs gets the correct answer.

Yes it can!
If you are running behind Nginx, Caddy, Squid, or Apache, make sure you pass `X-Forwarded-For` or `X-Real-IP` correctly.

**Comment by lightsing** [comment]
I mean the doh-client part acctually. (faceplam
Also, if doh-client is running behind NAT, how to tell it the subnet?

**Comment by m13253** [comment]
> I mean the doh-client part acctually. (faceplam

Both doh-client and doh-server cooperate to detect the IP address. That's why I suggest using doh-client and doh-server together, instead of using compatible software written by other people (although they basically work).

By the way, the CloudFlare public server does not support ECS by design. They said it is for privacy.

Google's experimental server supports ECS, but you certainly does not connect to Google directly from China, right? Just set up a pair of doh-server + doh-client on the bouncer machine, then your IP address can be detected correctly.

**Comment by lightsing** [comment]
I'm afraid i can't agree with this. Let me keep these changes as a fork. thx.

**Comment by m13253** [comment]
That's cool!

It will be very nice if there are forks -- more choices are usually better.

Actually we are discussing about ECS along with other privacy concerns these weeks in DoH official mail list. Maybe I was wrong, I will reconsider this feature after the discussion.

**Comment by m13253** [comment]
Hello,

I am sorry to interrupt you.

I come here because I recently received other feature requests, but most of the time what they want is to manipulate DNS packets **in a traditional manner** (such as modifying some values in the DNS packet) -- which is pretty similar to your contribution.

I don't really want to integrate DNS modification features right into DoH. Because if you really want to modify in a traditional manner, why not use a traditional DNS manipulation software, which is way more powerful, easy to use, and professional?

Here is an example configuration for [dnsdist](https://dnsdist.org):

```lua
newServer({address="127.0.0.1:5380", useClientSubnet=true})
newServer({address="[::1]:5380", useClientSubnet=true})

getPool(""):setCache(newPacketCache(10000))

addAction(AllRule(), SetECSAction("223.5.5.0/24"))
```

I encourage you to always equip your server with some software like [dnsdist](https://dnsdist.org), because it can also do caching and offers DDoS protection.

Thank you.

**Comment by lightsing** [comment]
Thanks.

**Pull request closed without merging**
