### PR TITLE
chore: unnecessary use of fmt.Sprintf

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Comment by GreyXor** [comment]
Thanks @testwill :)

**Comment by m13253** [comment]
Thanks for the contribution!

I appreciate it!

**Comment by vinnyperella** [comment]
That string exists elsewhere in that file is that the only place it needs removed? For example:

> return &DNSRequest{
			errcode: 400,
			errtext: fmt.Sprintf("Invalid argument value: \"dns\" = %q", requestBase64),

**Comment by m13253** [comment]
I think the occurrence with %q you pointed out is how Sprintf is supposed to be used.

That’s good as is in my opinion.

**Pull request merged**
