### PR TITLE
Add Dockerfiles

### PR DESCRIPTION
**Pull request by jangrewe**
Maybe this is of use to somebody...

### CODE REVIEW

**Comment by rwv** [comment]
Failed to run

```
2019/05/16 17:08:09 listen tcp [::1]:8053: bind: cannot assign requested address
```

* Docker Version: 18.09.2

----

Also, any idea to write an entry script that can access both `doh-server` and `doh-client`?
Or use `/doh-sever` directly like [this](https://github.com/rwv/docker-dns-over-https)?

**Comment by jangrewe** [comment]
Can you show me your complete command line? It works perfectly fine on `18.09.3` when ran without any arguments or parameters (so with the default config, just publishing the port), or when ran with a config mounted that makes it listen on `0.0.0.0:8053` (inside the container). You can't listen on both 0.0.0.0 and [::], of course, but 0.0.0.0 and [::1] works fine.

```
docker run -p 8053:8053 dns-over-https:latest
```

I don't have any control over what kind of invalid/unusable configs people mount into the container, so i made sure that at least the included default works. ;-)

Regarding a dual-use image:
You have the option of using the shell as the entrypoint and either doh-client or doh-server as an argument, preferably with one of them set as the CMD, or using a script as the entrypoint that will default to one of them with some sane arguments, but allows overriding them.

I prefer to treat my Docker images just like binaries they include, so that i can just run a container - and pass arguments if needed. That requires using the binary as the entrypoint, though.

**Comment by m13253** [comment]
> You can't listen on both 0.0.0.0 and [::], of course, but 0.0.0.0 and [::1] works fine.

Just to mention that, in order to listen on both `0.0.0.0:8053` and `[::]:8053` in Go, you can write `:8053` (without any IP address).

And please note that Docker [does not enable IPv6 by default](https://docs.docker.com/config/daemon/ipv6/). I recommend anyone who runs a DNS service enable outbound IPv6 support since it's already 2019, or better, both inbound and outbound IPv6.
So I hope this Dockerfile can check and print warning for system administrators who forget to enable IPv6 for Docker.

**Comment by m13253** [comment]
I just pushed the commit cb64f6694b905ba24fb242f29b1d04b10fa8c08e to teach the user how to listen on both IPv4 and IPv6.

@jangrewe would you please check whether your RegExp still works on the new version?

And… I hope we can print some warning if IPv6 support is disabled in Docker. Do you agree with me, or have comments about my opinion?

**Comment by jangrewe** [comment]
I'll push a new commit in a second, that will a) split the Dockerfile for server and client, and b) replace the listen addresses with only the ports. Your commit shouldn't affect the regex. ;-)

**Comment by m13253** [comment]
> I'll push a new commit in a second, that will a) split the Dockerfile for server and client, and b) replace the listen addresses with only the ports. Your commit shouldn't affect the regex. ;-)

Thank you for your quick reply!
I will check and merge after waking up.

**Comment by rwv** [comment]
From my experience, when you use `-p 53:53` it doesn’t matter whether the internal service listen on ipv6. It will listen on both ipv4 and ipv6 by default.

**Pull request merged**
