### PR TITLE
Added example configuration for Docker Flow Proxy + Docker

### PR DESCRIPTION
**Pull request by satishweb**
I would like to add an example for docker based doh-server setup. I had been using this setup since last 5 months and I believe this will make things easier for people who wants to use docker for setting up DoH server. Please let me know if I need to add more information or correct any information in documentation.

### CODE REVIEW

**Comment by m13253** [comment]
Thank you for your contribution!

Just before I merge this commit, I would like to confirm that, have you tried whether the configuration works with IPv6?

I know that Docker Swarm has a bad reputation of IPv6 support (maybe only in the past), but IPv6 support is very important to DNS services. So, would you please give me some information about this topic?

**Comment by satishweb** [comment]
IPV6 support is not available for Docker Swarm yet.

I can add this note in the documentation: "only IPV4 is supported by Docker Swarm as of now.".
I will add a link to Docker Swarm issue discussion thread. When Docker Swarm adds support for IPV6 in future, this docker example will work for IPV6.

Another option for me is to convert all of this into a Docker Compose with IPV6 without the use of Docker Swarm. If you think it makes sense, I can send another update as new pull request later. Please let me know what you think.

**Comment by m13253** [comment]
> IPV6 support is not available for Docker Swarm yet.

It's a pity :-(

> I can add this note in the documentation: "only IPV4 is supported by Docker Swarm as of now.".
> I will add a link to Docker Swarm issue discussion thread. When Docker Swarm adds support for IPV6 in future, this docker example will work for IPV6.

This is a good solution.

> Another option for me is to convert all of this into a Docker Compose with IPV6 without the use of Docker Swarm. If you think it makes sense, I can send another update as new pull request later. Please let me know what you think.

I think, this is a better solution compared with the previous one.

**Comment by satishweb** [comment]
I did some tests with docker-compose + IPV6 support. Looks like proxy needs to change and this should be a separate example altogether.

This docker swarm based example is still faster to setup. I believe that this example without IPV6 will be useful to majority of the users who intend to setup their private DNS server with DoH on Docker. IPV6 with docker compose setup will require more time and additional settings. This deserves it's own section in the documentation. I will work on that this weekend and add it as new example in this documentation. I will create new Pull Request for that.

Please review and accept new changes:
1. Added IPV6 Support info and link to related open issue
2. Added simple docker use example in installing section for those who just want to run DoH server.

**Comment by m13253** [comment]
Thank you for your contribution! Merged.

**Pull request merged**
