### PR TITLE
chore: upgrade deps

### PR DESCRIPTION
**Pull request by GreyXor**

### CODE REVIEW

**Comment by m13253** [comment]
Thanks for being a frequent contributor.
I'm starting to think of inviting more people to help me with the maintenance, do you mind if I invite you to the write access group of this repo?

**Comment by GreyXor** [comment]
> Thanks for being a frequent contributor. I'm starting to think of inviting more people to help me with the maintenance, do you mind if I invite you to the write access group of this repo?

Hello and thank you @m13253,
I can help however I can. Would this give me a right to automatically merge my PR? You know, as you answer fast enough, I don't mind waiting on you to merge my PR ;) so feel free to.

**Comment by m13253** [comment]
> Would this give me a right to automatically merge my PR?

Yes. You will be able to click the merge button after you gain the write access.

**Comment by GreyXor** [comment]
Alright, yes sounds good. thanks

**Comment by m13253** [comment]
> Alright, yes sounds good. thanks

Check your email for an invitation.

**Pull request merged**
