### PR TITLE
Separate doh googel api

### PR DESCRIPTION
**Pull request by sanyo0714**
_Google Public DNS provides two distinct DoH APIs at these endpoints:
https://dns.google/dns-query – RFC 8484 (GET and POST)
https://dns.google/resolve? – JSON API (GET)
from [https://developers.google.com/speed/public-dns/docs/doh]_

Make some changes according to the document.

### CODE REVIEW

**Comment by m13253** [comment]
The JSON API is already supported, even before RFC 8484 is a thing.

**Comment by sanyo0714** [comment]
> The JSON API is already supported many years ago,
> even before RFC 8484 is a thing.

That's true, but now it's happening together.
I think RFC8484 and JSON API need to be identified and addressed separately,  because the LOGIC of the RFC8484 and JSON API implementation is different.

**Comment by m13253** [comment]
I'm not quite sure what you mean by "separately". So the following contents are based on my interpretation.
If you want to have DoH on different paths, you can either run multiple doh-server instances, or use uri_rewrite on your nginx or Apache or Caddy side.

**Comment by sanyo0714** [comment]
> I'm not quite sure what you mean by "separately". So the following contents are based on my interpretation.
> If you want to have DoH on different paths, you can either run multiple doh-server instances, or use uri_rewrite on your nginx or Apache or Caddy side.

I want to have DoH on different paths at a doh-server instance.
If run multiple doh-server instances, the cache will not be Shared.

**Comment by m13253** [comment]
doh-server does not have cache. That's to complicated. To make things worse, in order to support ECS, the cache algorithm would be more complex.
So you will need to run a cache yourself, and connect two instances into the same cache.

**Pull request closed without merging**
