### PR TITLE
Linux (Ubuntu) easy install

### PR DESCRIPTION
**Pull request by joubin**
Added instructions and script for easy installation under Ubuntu
Tested with:

  * Ubuntu 16.04 LTS
  * Raspbian (Jesse, Pi 3 B+)

### CODE REVIEW

**Comment by m13253** [comment]
Thank you for your contribution!

But in order to merge your work into the repo, I would like to propose several issues:

1. In Line 5, you said version "1.7". I guess it is a typo. Did you probably meant version 1.10?

2. Please mind your spelling. It is "Go" or "Golang" ("Go" is preferred), instead of "Go-Lang".

3. Please make sure you do not have extra empty lines at the end of your files. They don't look nice.

4. You may try to use `set -e` in your scripts so it stops whenever an error happens. Then you may omit `&&`.

5. Use `sudo` in Line 47 of`linux-install.md`.

6. I want to put it in `docs` folder and refer to it in `Readme.md` so the root folder look neat. Do you agree with me? (Or optionally capitalize the file name of `linux-install.md` to make it top-listed.)

Anyway, I think a better way is to provide pre-built `.deb` packages. It may be achieved by using a CI service, or include `dns-over-https` in a distro's repo. Would you please help me with it?

**Comment by m13253** [comment]
Thank you for your improvements!

**Comment by m13253** [comment]
I think the best way is to provide prebuilt packages so the user can download and install it in less than a minute.

I am currently figuring out how to use a CI service to build ".deb" packages for me. When I successfully build the packages in the future, I would like to replace the installation guide with a much simpler version.

(P.S. Since the replacement would remove your existing lines. What else do you think I can do to credit the work to your contributions?)

**Comment by joubin** [comment]
@m13253... No worries about credit... Just glad that I was able to help for now.

**Comment by m13253** [comment]
An RFP has been submitted to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896807

Hopefully we can see dns-over-https in Debian main repository by the end of this century. 😆

**Pull request merged**
