### PR TITLE
log real client ip behind a HTTPS gateway

### PR DESCRIPTION
**Pull request by qyb**
pull again, with better compatible for apache/nginx log default format

### CODE REVIEW

**Comment by qyb** [comment]
Should we add a log-realip option in doh-server.conf ?

**Comment by m13253** [comment]
Thank you for the update.

Just to mention that X-Forwarded-For can be forged.
It is okay for doh-server to receive a forged X-Forwarded-For for ECS purpose.

But I am afraid it is better that we can log the full IP chain? (RemoteIP + X-Real-IP + X-Forwarded, separated with comma)

**Comment by qyb** [comment]
RemoteIP + X-Real-IP + X-Forwarded .. is unuseable.

My suggestion is setting a doh-server.conf option. This feature default is off. Then system administrator will config their nginx/apache to remove forge http header and enable it..

**Comment by m13253** [comment]
> My suggestion is setting a doh-server.conf option. This feature default is off. Then system administrator will config their nginx/apache to remove forge http header and enable it..

That's a good idea!

I want to name it as "log_guessed_client_ip" in `doh-server.conf`. The word "guess" indicates that it is not always accurate.
What's your opinion?

Would you like to implement it, or wait a few days until I have time to implement it?

**Comment by qyb** [comment]
done!

**Pull request merged**
